services:
  - type: web
    name: samsung-galaxy-showcase-api
    runtime: node
    rootDir: samsung-galaxy-showcase/server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
